---
- name: Block
  block:
    - name: Create code directory
      file:
        dest: "{{ code_dir }}"
        state: directory

    - name: Get latest application code from Github
      git:
        repo: "git@github.com:{{ repo_name }}"
        version: "{{ branch_name }}"
        dest: "{{ code_dir }}"

    - name: Secure Login to DockerHub
      docker_login:
        username: "{{ dockerhub_user }}"
        password: "{{ dockerhub_pass }}"

    - name: Build Docker image
      docker_image:
        build:
          path: "{{ code_dir }}"
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: yes
        source: build
        state: present

    - name: Run Docker container
      docker_container:
        name: "{{ app_name }}"
        state: started
        image: "{{ image_name }}:{{ image_tag }}"
        pull: true
        ports:
           - "{{ listen_port }}:{{ listen_port }}"
        env: 
          PORT: "{{ listen_port | string }}"
        healthcheck:
          test: ["CMD", "curl", "--fail", "http://localhost:{{ listen_port }}"]
          interval: 10s
          retries: 2
          start_period: 5s
  
  rescue:
    - name: Delete code directory
      file:
        dest: "{{ code_dir }}"
        state: absent
