- name: Deploy flask app
  hosts: localhost
  gather_facts: no
  become: no

  vars_files:
    - secrets.yaml
    
  vars:
    repo_name: "eevlogiev/devops-telerik" 
    branch_name: "main"
 
  roles:
    - role: roles/flask
