---
name: Homework Demo
run-name: ${{ github.actor }} is running his Homework
on:
      pull_request:
          paths:
            - '**.yaml'

jobs:
      yamllint:
          name: 'Yamllint'
          runs-on: ubuntu-latest
          steps:
            - name: 'Checkout'
              uses: actions/checkout@v4
            - name: 'Yamllint'
              uses: karancode/yamllint-github-action@master
        